### PR TITLE
Feat/main menu

### PR DESCRIPTION
**Pull request by iamgruuten**
## Description
The Main Menu feature has been added to the main program. 

**Features**:
The menu selection function takes in input from the user.

option 1 - run start game func
option 2 - run load game func
option 0 - exit game

## Screenshots
**BEFORE**:
No terminal output

**AFTER**:
image

## Test ##
Unit Test on MenuSelection Function

UT 1: Pass in "1" as args to MenuSelection Function, Expected Outcome StartGame Function is called
UT 2: Pass in "2" as args to MenuSelection Function, Expected Outcome LoadGame Function is called
UT 3: Pass in "0" as args to MenuSelection Function, Expected Outcome Exit Function is called
UT 4: Pass in invalid args (e.g. args not 1,2,0), Expected Outcome StartGame Function is called

### CODE REVIEW

**Review by DannyOnCode — CHANGES_REQUESTED** [review]
Reject

**Comment by iamgruuten** [comment]
I have successfully passed the QA test

**Review by iamgruuten — COMMENTED** [review]
I have viewed the files and ensure that it pass the quality check

**Review by DannyOnCode — APPROVED** [review]
lgtm

**Pull request merged**
